/**
 * Generate a CSS override file string from direct and derived token overrides.
 */
export function generateCss(
  themeName: string,
  directOverrides: Map<string, string>,
  derivedOverrides: Map<string, string>
): string {
  const timestamp = new Date().toISOString();
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * ${themeName} Theme Override`);
  lines.push(` *`);
  lines.push(` * Generated by: @uiid/themes`);
  lines.push(` * Generated on: ${timestamp}`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`:root {`);

  // Direct theme token overrides
  lines.push(`  /* Theme tokens */`);
  for (const [cssVar, value] of directOverrides) {
    lines.push(`  ${cssVar}: ${value};`);
  }

  // Derived shade/tone overrides
  if (derivedOverrides.size > 0) {
    lines.push(``);
    lines.push(`  /* Derived shade + tone tokens */`);
    for (const [cssVar, value] of derivedOverrides) {
      lines.push(`  ${cssVar}: ${value};`);
    }
  }

  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}
