// The icon set, served as `@uiid/design-system/icons` so it stays out of the root
// barrel — importing a component from this package must never pull the icon set
// into a consumer's module graph.
//
// Consumers of this package can also reach a single icon directly:
//
//   import { GlobeIcon } from "@uiid/design-system/icons/globe";
//
// which parses one lucide module rather than ~1,768. Those subpaths are thin
// forwarders onto `@uiid/icons/<icon>`, generated by
// scripts/emit-icon-forwarders.mjs.
export * from "@uiid/icons";
