/**
 * Generate a CSS override file string from direct and derived token overrides.
 *
 * @param {string} themeName
 * @param {Map<string, string>} directOverrides
 * @param {Map<string, string>} derivedOverrides
 * @returns {string}
 */
export function generateCss(themeName, directOverrides, derivedOverrides) {
  const timestamp = new Date().toISOString();
  const lines = [];

  lines.push(`/**`);
  lines.push(` * ${themeName} Theme Override`);
  lines.push(` *`);
  lines.push(` * Generated by: npx tsx scripts/generate-theme.js`);
  lines.push(` * Generated on: ${timestamp}`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`:root {`);

  // Direct theme token overrides
  lines.push(`  /* Theme tokens */`);
  for (const [cssVar, value] of directOverrides) {
    lines.push(`  ${cssVar}: ${value};`);
  }

  // Derived shade overrides
  if (derivedOverrides.size > 0) {
    lines.push(``);
    lines.push(`  /* Derived shade tokens */`);
    for (const [cssVar, value] of derivedOverrides) {
      lines.push(`  ${cssVar}: ${value};`);
    }
  }

  lines.push(`}`);
  lines.push(``);

  return lines.join("\n");
}
