#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import StyleDictionary from "style-dictionary";
import { formattedVariables } from "style-dictionary/utils";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tokensRoot = path.resolve(__dirname, "src");
const jsonDir = path.join(tokensRoot, "json");
const cssDir = path.join(tokensRoot, "css");

const LAYER = "uiid.tokens";

/** Recursively find every *.tokens.json under json/, keeping its path relative to json/. */
function discoverTokenFiles(dir, relativePath = "") {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    const rel = path.join(relativePath, entry.name);
    if (entry.isDirectory()) return discoverTokenFiles(full, rel);
    return entry.isFile() && entry.name.endsWith(".tokens.json")
      ? [
          {
            fullPath: full,
            relativePath: rel,
            name: path.parse(entry.name).name.replace(/\.tokens$/, ""),
          },
        ]
      : [];
  });
}

/** Render a token reference "{a.b.c}" as var(--a-b-c); pass anything else through. */
function refToVar(value) {
  return typeof value === "string"
    ? value.replace(
        /\{([^}]+)\}/g,
        (_m, p) => `var(--${p.replace(/\./g, "-")})`,
      )
    : String(value);
}

function shadowToCss(shadow) {
  const parts = [];
  if (shadow.inset) parts.push("inset");
  parts.push(
    refToVar(shadow.offsetX),
    refToVar(shadow.offsetY),
    refToVar(shadow.blur),
  );
  if (shadow.spread) parts.push(refToVar(shadow.spread));
  parts.push(refToVar(shadow.color));
  return parts.join(" ");
}

/** Token path → CSS custom property name. camelCase segments (from expanded
 *  composites, e.g. fontSize) become kebab-case; existing keys pass through. */
StyleDictionary.registerTransform({
  name: "uiid/name-path",
  type: "name",
  transform: (token) =>
    token.path
      .map((p) => p.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase())
      .join("-"),
});

/** org.uiid.derive light-dark → light-dark(<light>, <dark>).
 *  $extensions are not reference-resolved by Style Dictionary, so the
 *  {a.b} → var(--a-b) rewrite is done here, as the previous generator did. */
StyleDictionary.registerTransform({
  name: "uiid/derive-light-dark",
  type: "value",
  transitive: true,
  filter: (token) =>
    token.$extensions?.["org.uiid.derive"]?.method === "light-dark",
  transform: (token) => {
    const d = token.$extensions["org.uiid.derive"];
    return `light-dark(${refToVar(d.light)}, ${refToVar(d.dark)})`;
  },
});

/** DTCG cubicBezier is [x1, y1, x2, y2]. */
StyleDictionary.registerTransform({
  name: "uiid/cubic-bezier",
  type: "value",
  filter: (token) =>
    token.$type === "cubicBezier" && Array.isArray(token.$value),
  transform: (token) => `cubic-bezier(${token.$value.join(", ")})`,
});

/** DTCG shadow: a single object or an array of them (layered). */
StyleDictionary.registerTransform({
  name: "uiid/shadow",
  type: "value",
  filter: (token) =>
    token.$type === "shadow" && typeof token.$value === "object",
  transform: (token) =>
    Array.isArray(token.$value)
      ? token.$value.map(shadowToCss).join(", ")
      : shadowToCss(token.$value),
});

/** Wrap the custom properties in the design system's cascade layer. */
StyleDictionary.registerFormat({
  name: "uiid/css-layer",
  format: ({ dictionary, options }) => {
    const { title, description, sourceRelPath } = options;
    const header = `/**
 * ${title} Tokens
 * ${description}
 *
 * 🚨 AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Generated from: json/${sourceRelPath}
 * Generated by: packages/tokens/build-tokens.js
 */`;
    const vars = formattedVariables({
      format: "css",
      dictionary,
      outputReferences: true,
      usesDtcg: true,
      formatting: { indentation: "    " },
    });
    return `${header}\n\n@layer ${LAYER} {\n  :root {\n${vars.trimEnd()}\n  }\n}\n`;
  },
});

const titleize = (name) =>
  name
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

const sourceFiles = discoverTokenFiles(jsonDir);
if (sourceFiles.length === 0) {
  console.log("⚠️  No JSON token files found in", jsonDir);
  process.exit(0);
}

const files = sourceFiles.map((f) => {
  const meta = JSON.parse(fs.readFileSync(f.fullPath, "utf8"));
  const title = titleize(f.name);
  return {
    destination: f.relativePath.replace(/\.tokens\.json$/, ".tokens.css"),
    format: "uiid/css-layer",
    // One output per source file; references still resolve across the whole set.
    filter: (token) => token.filePath === f.fullPath,
    options: {
      title,
      description:
        meta.$description || `${title} tokens for the UIID design system`,
      sourceRelPath: f.relativePath,
    },
  };
});

const sd = new StyleDictionary({
  source: sourceFiles.map((f) => f.fullPath),
  // Only typography decomposes into per-property vars; shadows stay composed.
  expand: { include: ["typography"] },
  platforms: {
    css: {
      buildPath: `${cssDir}/`,
      transforms: [
        "uiid/name-path",
        "uiid/derive-light-dark",
        "uiid/cubic-bezier",
        "uiid/shadow",
      ],
      files,
    },
  },
});

console.log("🎨 Generating CSS tokens from JSON...\n");
await sd.buildAllPlatforms();

// Prune orphaned CSS left behind by deleted token files. Done after a
// successful build so a failed one never destroys usable output.
const expected = new Set(files.map((f) => path.join(cssDir, f.destination)));
const prune = (dir) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      prune(full);
      if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
    } else if (entry.name.endsWith(".css") && !expected.has(full)) {
      fs.unlinkSync(full);
      console.log(`   removed orphan: ${path.relative(cssDir, full)}`);
    }
  }
};
if (fs.existsSync(cssDir)) prune(cssDir);

console.log(`\n✅ Token generation complete: ${files.length} files`);
